name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 8 * * *

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        ref: master

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Build
      id: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "RELEASE_NAME=$(date '+%Y年%m月%d日 更新')" >> $GITHUB_OUTPUT
        echo "RELEASE_TAG=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
        python main.py
        tar -cvf sdcard.tar.gz sdcard

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ steps.build.outputs.RELEASE_NAME }}
        tag: ${{ steps.build.outputs.RELEASE_TAG }}
        allowUpdates: true
        bodyFile: "description.txt"
        artifacts: "sdcard.tar.gz"
        commit: master
